language: node_js
node_js:
- stable
npm: true
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
   secure: fOD5vWiZYw6QS2OYYpkiD6gvN4B/hHfrsrVTLBjkc5DuenLSJoc5gIkCL7vi/0oe3rCaLIam+KlHvjt8wfgLzOANaDxNJtXX4YLFqU/xVW0hP8fa2KSFoOLrjC54vcjnMC8e88MA40ZBMwJyUgqsVJjIgXMRBEj87DOVNjhykE0Xaa1ENq7jL3MLhBjP0T8poIa+G3ExpS4V1OAOwj2oSPKMWF8IYBddM0C80Zajl/K10qKjX4kuXTpIWS6fFRGbslm6WdcCMaXFUgOuFFz2WYVN+GFTBgfZSc02duEQCGdfFmL9XDqsw3uy4FxYuIiZIW5mL+JjV8cDK930E3IGW+5U4NbvC+vuBjql3NbSG4NfdqQ+AXlUgbavi+PxNmZSwYJ0XLI+JJev30pYEpRayl1TAqfI4ovJux6Wmy2b9MZewycPNSJnIQbm3jnELvDQs/Z3QrYMkx7VSVSkWJ16tlzV7Z+2UJ9VwUzYIPGH6exz7zr76clNf7XPTOEoRnIy9wOqZVtwl5MXIbhawHiSpdt/dn8vljS7BUhKfOf5Ii3ZXoqZALdutWtAY1yEL95zc5+HGzf/dHoohv1szPiTRNdFSvbLZMR7hwY577XILEGJ0XIysJqIaa/H7t5jYbZfEsvUf5BxWR8YPVkaMIiICzpYPBOZDRTLD/Cg0f5CymI=
  app: obscure-woodland-90036
  on:
    repo: legendarybrij/sample-travis-heroku
    
